-- MySQL Script generated by MySQL Workbench
-- 03/06/19 22:15:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cdc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cdc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdc` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `cdc` ;

-- -----------------------------------------------------
-- Table `cdc`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`ROL` ;

CREATE TABLE IF NOT EXISTS `cdc`.`ROL` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`USUARIO` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `Rol_rol_id` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `sexo` INT NULL,
  `fechaNacimiento` DATETIME NULL,
  `email` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_USUARIO_Rol1_idx` (`Rol_rol_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_USUARIO_Rol1`
    FOREIGN KEY (`Rol_rol_id`)
    REFERENCES `cdc`.`ROL` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`ELEMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`ELEMENTO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`ELEMENTO` (
  `elemento_id` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_usuario_id` INT NULL,
  `codigo` VARCHAR(45) NULL,
  `nombrecomun` VARCHAR(45) NULL,
  `nombrecientifico` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`elemento_id`),
  INDEX `fk_ELEMENTO_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_ELEMENTO_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`RASTREO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`RASTREO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`RASTREO` (
  `rastreo_id` INT NOT NULL AUTO_INCREMENT,
  `codigoe` VARCHAR(45) NULL,
  `tropicos` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `subnacion` VARCHAR(45) NULL,
  `clasetax` VARCHAR(45) NULL,
  `orden` VARCHAR(45) NULL,
  `familia` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `nombreg` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `fuentenom` INT NULL,
  `refnombreg` VARCHAR(45) NULL,
  `disttax` VARCHAR(45) NULL,
  `dudatax` VARCHAR(45) NULL,
  `nomcomung` VARCHAR(45) NULL,
  `comtaxg` VARCHAR(45) NULL,
  `nombren` VARCHAR(45) NULL,
  `numsinn` INT NULL,
  `nomcomunn` VARCHAR(45) NULL,
  `comtaxn` VARCHAR(45) NULL,
  `rangog` VARCHAR(45) NULL,
  `fecharevrg` DATETIME NULL,
  `formularg` VARCHAR(45) NULL,
  `resprg` VARCHAR(45) NULL,
  `aepeu` VARCHAR(45) NULL,
  `fechaaepeu` DATETIME NULL,
  `cites` VARCHAR(45) NULL,
  `iucn` VARCHAR(45) NULL,
  `planscons` VARCHAR(45) NULL,
  `resplan` VARCHAR(45) NULL,
  `resumenman` VARCHAR(45) NULL,
  `resresumen` VARCHAR(45) NULL,
  `exsitu` TINYINT(1) NULL,
  `instexsitu` VARCHAR(45) NULL,
  `endemismo` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `fecharevrn` DATETIME NULL,
  `formularn` VARCHAR(45) NULL,
  `rastreolen` VARCHAR(45) NULL,
  `lestimn` VARCHAR(45) NULL,
  `leprotn` VARCHAR(45) NULL,
  `abundn` VARCHAR(45) NULL,
  `protnacion` VARCHAR(45) NULL,
  `refnombren` VARCHAR(45) NULL,
  `transparencian` TINYINT(1) NULL,
  `rangos` VARCHAR(45) NULL,
  `fecharevrs` DATETIME NULL,
  `formulars` VARCHAR(45) NULL,
  `rastreoles` VARCHAR(45) NULL,
  `lestims` VARCHAR(45) NULL,
  `leprots` VARCHAR(45) NULL,
  `abunds` VARCHAR(45) NULL,
  `protsubnac` VARCHAR(45) NULL,
  `refnombres` VARCHAR(45) NULL,
  `transparencias` TINYINT(1) NULL,
  `reopc1` VARCHAR(45) NULL,
  `reopc2` VARCHAR(45) NULL,
  `reopc3` VARCHAR(45) NULL,
  `reopc4` VARCHAR(45) NULL,
  `reopc5` VARCHAR(45) NULL,
  `codfuenten` VARCHAR(45) NULL,
  `codfuentes` VARCHAR(45) NULL,
  `actualizag` DATETIME NULL,
  `actualizan` DATETIME NULL,
  `actualizas` DATETIME NULL,
  `ELEMENTO_elemento_id` INT NULL,
  PRIMARY KEY (`rastreo_id`),
  INDEX `fk_RASTREO_ELEMENTO1_idx` (`ELEMENTO_elemento_id` ASC),
  UNIQUE INDEX `codigoe_UNIQUE` (`codigoe` ASC),
  CONSTRAINT `fk_RASTREO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elemento_id`)
    REFERENCES `cdc`.`ELEMENTO` (`elemento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`LOCALIZACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`LOCALIZACION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`LOCALIZACION` (
  `localizacion_id` INT NOT NULL AUTO_INCREMENT,
  `codigole` VARCHAR(45) NULL,
  `ident` TINYINT(1) NULL,
  `RASTREO_rastreo_id` INT NULL,
  `subnacion` VARCHAR(45) NULL,
  `subdivision` VARCHAR(45) NULL,
  `codsitio` VARCHAR(45) NULL,
  `nomsitio` VARCHAR(45) NULL,
  `sitioeva` VARCHAR(45) NULL,
  `precisionl` VARCHAR(45) NULL,
  `nommapa` VARCHAR(45) NULL,
  `codmapa` VARCHAR(45) NULL,
  `nummarg` VARCHAR(45) NULL,
  `numpunto` VARCHAR(45) NULL,
  `diezdiez` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `coords` VARCHAR(45) NULL,
  `coordn` VARCHAR(45) NULL,
  `coorde` VARCHAR(45) NULL,
  `coordo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `ecoregion` VARCHAR(45) NULL,
  `cuenca` VARCHAR(45) NULL,
  `fechaeva` DATETIME NULL,
  `ultobs` DATETIME NULL,
  `priobs` VARCHAR(45) NULL,
  `rangole` VARCHAR(2) NULL,
  `fecharangole` DATETIME NULL,
  `comrangole` VARCHAR(45) NULL,
  `datosle` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `numcontacto` VARCHAR(45) NULL,
  `desgen` VARCHAR(45) NULL,
  `elev` INT NULL,
  `area` INT NULL,
  `masterreno` TINYINT(1) NULL,
  `masprotec` TINYINT(1) NULL,
  `masmanejo` TINYINT(1) NULL,
  `involtnc` TINYINT(1) NULL,
  `commanejo` VARCHAR(45) NULL,
  `comprot` VARCHAR(45) NULL,
  `prop` VARCHAR(45) NULL,
  `infprop` TINYINT(1) NULL,
  `comprop` VARCHAR(45) NULL,
  `leopc1` VARCHAR(45) NULL,
  `leopc2` VARCHAR(45) NULL,
  `leopc3` VARCHAR(45) NULL,
  `leopc4` VARCHAR(45) NULL,
  `leopc5` VARCHAR(45) NULL,
  `leopc6` VARCHAR(45) NULL,
  `leopc7` VARCHAR(45) NULL,
  `leopc8` VARCHAR(45) NULL,
  `leopc9` VARCHAR(45) NULL,
  `leopc10` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  `sensdatos` TINYINT(1) NULL,
  `limites` TINYINT(1) NULL,
  `fotos` TINYINT(1) NULL,
  `mejorfuente` VARCHAR(45) NULL,
  `codfuente` VARCHAR(45) NULL,
  `mdrev` TINYINT(1) NULL,
  `transcrito` DATETIME NULL,
  `cc` TINYINT(1) NULL,
  `cartografo` DATETIME NULL,
  `respdatos` DATETIME NULL,
  `actualizar` DATETIME NULL,
  `nombres` VARCHAR(45) NULL,
  `nomcomuns` VARCHAR(45) NULL,
  `rangog` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `rangos` VARCHAR(45) NULL,
  PRIMARY KEY (`localizacion_id`),
  INDEX `fk_LOCALIZACION_RASTREO1_idx` (`RASTREO_rastreo_id` ASC),
  UNIQUE INDEX `codigole_UNIQUE` (`codigole` ASC),
  CONSTRAINT `fk_LOCALIZACION_RASTREO1`
    FOREIGN KEY (`RASTREO_rastreo_id`)
    REFERENCES `cdc`.`RASTREO` (`rastreo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`AREA` ;

CREATE TABLE IF NOT EXISTS `cdc`.`AREA` (
  `area_id` INT NOT NULL AUTO_INCREMENT,
  `codigoam` VARCHAR(45) NULL,
  `nombream` VARCHAR(45) NULL,
  `sinam` VARCHAR(45) NULL,
  `ammayor` VARCHAR(45) NULL,
  `coddueno` VARCHAR(45) NULL,
  `codsitio` VARCHAR(45) NULL,
  `nomsitio` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `subnacion` VARCHAR(45) NULL,
  `subdivision` VARCHAR(45) NULL,
  `nommapa` VARCHAR(45) NULL,
  `codmapa` VARCHAR(45) NULL,
  `nummarg` VARCHAR(45) NULL,
  `lat` VARCHAR(45) NULL,
  `long1` VARCHAR(45) NULL,
  `coords` VARCHAR(45) NULL,
  `coordn` VARCHAR(45) NULL,
  `coorde` VARCHAR(45) NULL,
  `coordo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `areatot1` INT NULL,
  `areatot2` INT NULL,
  `areasubnac1` INT NULL,
  `areasubnac2` INT NULL,
  `multisubnac` TINYINT(1) NULL,
  `limites` TINYINT(1) NULL,
  `continua` TINYINT(1) NULL,
  `involtnc` TINYINT(1) NULL,
  `comentario` VARCHAR(45) NULL,
  `fechaesta` DATETIME NULL,
  `protasign` VARCHAR(1) NULL,
  `administrador` VARCHAR(45) NULL,
  `instadmin` VARCHAR(45) NULL,
  `diradmin1` VARCHAR(45) NULL,
  `diradmin2` VARCHAR(45) NULL,
  `ciudadadmin` VARCHAR(45) NULL,
  `subnacadmin` VARCHAR(45) NULL,
  `codpostaladmin` VARCHAR(45) NULL,
  `telefadminist` VARCHAR(45) NULL,
  `accesopub` VARCHAR(1) NULL,
  `instcoop` VARCHAR(45) NULL,
  `commanejo` VARCHAR(45) NULL,
  `amopc1` VARCHAR(45) NULL,
  `amopc2` VARCHAR(45) NULL,
  `amopc3` VARCHAR(45) NULL,
  `amopc4` VARCHAR(45) NULL,
  `amopc5` VARCHAR(45) NULL,
  `respdatos` VARCHAR(45) NULL,
  `actualizar` DATETIME NULL,
  `USUARIO_usuario_id` INT NULL,
  PRIMARY KEY (`area_id`),
  UNIQUE INDEX `codigoam_UNIQUE` (`codigoam` ASC),
  INDEX `fk_AREA_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  CONSTRAINT `fk_AREA_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`SITIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`SITIO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`SITIO` (
  `sitio_id` INT NOT NULL AUTO_INCREMENT,
  `codsitio` VARCHAR(45) NULL,
  `nomsitio` VARCHAR(45) NULL,
  `sinsitio` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `subnacion` VARCHAR(45) NULL,
  `siteresp` VARCHAR(45) NULL,
  `lat` VARCHAR(45) NULL,
  `long1` VARCHAR(45) NULL,
  `coords` VARCHAR(45) NULL,
  `coordn` VARCHAR(45) NULL,
  `coorde` VARCHAR(45) NULL,
  `coordo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `descrito` VARCHAR(45) NULL,
  `mapasitio` VARCHAR(1) NULL,
  `fechamapa` DATETIME NULL,
  `dibujante` VARCHAR(45) NULL,
  `justlimite` VARCHAR(45) NULL,
  `areaprisec1` INT NULL,
  `areaprisec2` INT NULL,
  `areapri1` INT NULL,
  `areapri2` INT NULL,
  `areatotal1` INT NULL,
  `areatotal2` INT NULL,
  `comsitio` VARCHAR(45) NULL,
  `rangoant` VARCHAR(1) NULL,
  `comrango` VARCHAR(45) NULL,
  `impdivbiol` VARCHAR(2) NULL,
  `comdivbiol` VARCHAR(45) NULL,
  `impnodivbiol` VARCHAR(2) NULL,
  `comnodivbiol` VARCHAR(45) NULL,
  `urgencia` VARCHAR(2) NULL,
  `comurgencia` VARCHAR(45) NULL,
  `intenccons` VARCHAR(45) NULL,
  `numlotes` INT NULL,
  `costestprot1` INT NULL,
  `costestprot2` INT NULL,
  `coddesig` VARCHAR(45) NULL,
  `designacion` VARCHAR(45) NULL,
  `comprot` VARCHAR(45) NULL,
  `comusotierra` VARCHAR(45) NULL,
  `compeligrnat` VARCHAR(45) NULL,
  `comexoticas` VARCHAR(45) NULL,
  `usotierraf` VARCHAR(45) NULL,
  `necinform` VARCHAR(45) NULL,
  `necmanejo` VARCHAR(45) NULL,
  `comam` VARCHAR(45) NULL,
  `rbsopc1` VARCHAR(45) NULL,
  `rbsopc2` VARCHAR(45) NULL,
  `rbsopc3` VARCHAR(45) NULL,
  `rbsopc4` VARCHAR(45) NULL,
  `rbsopc5` VARCHAR(45) NULL,
  `respdatos` VARCHAR(45) NULL,
  `actualizar` DATETIME NULL,
  `USUARIO_usuario_id` INT NULL,
  PRIMARY KEY (`sitio_id`),
  UNIQUE INDEX `codsitio_UNIQUE` (`codsitio` ASC),
  INDEX `fk_SITIO_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  CONSTRAINT `fk_SITIO_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CONTACTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CONTACTO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CONTACTO` (
  `contacto_id` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_usuario_id` INT NULL,
  `numident` VARCHAR(45) NULL,
  `nombreident` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `sufijo` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dir1` VARCHAR(45) NULL,
  `dir2` VARCHAR(45) NULL,
  `dir3` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `subnacion` VARCHAR(45) NULL,
  `codpostal` VARCHAR(45) NULL,
  `masident` VARCHAR(45) NULL,
  `smsa` VARCHAR(45) NULL,
  `teleftrabajo` INT NULL,
  `telefhogar` INT NULL,
  `tipocont` VARCHAR(45) NULL,
  `activcont` VARCHAR(45) NULL,
  `resumen` VARCHAR(45) NULL,
  `coddirp` VARCHAR(45) NULL,
  `actualizar` DATETIME NULL,
  PRIMARY KEY (`contacto_id`),
  INDEX `fk_CONTACTOS_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  UNIQUE INDEX `numident_UNIQUE` (`numident` ASC),
  CONSTRAINT `fk_CONTACTOS_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`ACCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`ACCION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`ACCION` (
  `accion_id` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_usuario_id` INT NULL,
  PRIMARY KEY (`accion_id`),
  INDEX `fk_ACCION_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  CONSTRAINT `fk_ACCION_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`JERARQUIZACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`JERARQUIZACION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`JERARQUIZACION` (
  `jerarquizacion_id` INT NOT NULL AUTO_INCREMENT,
  `codigoe` VARCHAR(45) NULL,
  `ELEMENTO_elemento_id` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`jerarquizacion_id`),
  INDEX `fk_JERARQUIZACION_ELEMENTO1_idx` (`ELEMENTO_elemento_id` ASC),
  CONSTRAINT `fk_JERARQUIZACION_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elemento_id`)
    REFERENCES `cdc`.`ELEMENTO` (`elemento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`GLOBAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`GLOBAL` ;

CREATE TABLE IF NOT EXISTS `cdc`.`GLOBAL` (
  `global_id` INT NOT NULL AUTO_INCREMENT,
  `JERARQUIZACION_jerarquizacion_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nombreg` VARCHAR(45) NULL,
  `descrielem` VARCHAR(45) NULL,
  `especle` VARCHAR(45) NULL,
  `especranga` VARCHAR(45) NULL,
  `especrangb` VARCHAR(45) NULL,
  `especrangc` VARCHAR(45) NULL,
  `especrangd` VARCHAR(45) NULL,
  `habitat` VARCHAR(45) NULL,
  `permanencia` VARCHAR(45) NULL,
  `gloctip` VARCHAR(45) NULL,
  `comtax` VARCHAR(45) NULL,
  `glestim` VARCHAR(45) NULL,
  `glestimcom` VARCHAR(45) NULL,
  `gabund` VARCHAR(45) NULL,
  `gabundcom` VARCHAR(45) NULL,
  `gdist` VARCHAR(45) NULL,
  `gdistcom` VARCHAR(45) NULL,
  `gleprot` VARCHAR(45) NULL,
  `gleprotcom` VARCHAR(45) NULL,
  `gamenaz` VARCHAR(45) NULL,
  `gamenazcom` VARCHAR(45) NULL,
  `gfragil` VARCHAR(45) NULL,
  `gfragilcom` VARCHAR(45) NULL,
  `gotroconsi` VARCHAR(45) NULL,
  `rangog` VARCHAR(45) NULL,
  `fecharg` DATETIME NULL,
  `granrazon` VARCHAR(45) NULL,
  `gnecprotec` VARCHAR(45) NULL,
  `gnecinvent` VARCHAR(45) NULL,
  `gnecestudi` VARCHAR(45) NULL,
  `gnecmanejo` VARCHAR(45) NULL,
  `resrg` VARCHAR(45) NULL,
  `edautor` VARCHAR(45) NULL,
  `edicion` DATETIME NULL,
  `actualizar` DATETIME NULL,
  PRIMARY KEY (`global_id`),
  INDEX `fk_GLOBAL_JERARQUIZACION1_idx` (`JERARQUIZACION_jerarquizacion_id` ASC),
  CONSTRAINT `fk_GLOBAL_JERARQUIZACION1`
    FOREIGN KEY (`JERARQUIZACION_jerarquizacion_id`)
    REFERENCES `cdc`.`JERARQUIZACION` (`jerarquizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`NACIONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`NACIONAL` ;

CREATE TABLE IF NOT EXISTS `cdc`.`NACIONAL` (
  `nacional_id` INT NOT NULL AUTO_INCREMENT,
  `JERARQUIZACION_jerarquizacion_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nombren` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `nloctip` VARCHAR(45) NULL,
  `nlestim` VARCHAR(45) NULL,
  `nlestimcom` VARCHAR(45) NULL,
  `nabund` VARCHAR(45) NULL,
  `nabundcom` VARCHAR(45) NULL,
  `ndist` VARCHAR(45) NULL,
  `ndistcom` VARCHAR(45) NULL,
  `nleprot` VARCHAR(45) NULL,
  `nleprotcom` VARCHAR(45) NULL,
  `namenaz` VARCHAR(45) NULL,
  `namenazcom` VARCHAR(45) NULL,
  `notroconsi` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `fecharn` DATETIME NULL,
  `nranrzon` VARCHAR(45) NULL,
  `nnecprotec` VARCHAR(45) NULL,
  `nnecinvent` VARCHAR(45) NULL,
  `nnecestudi` VARCHAR(45) NULL,
  `nnecmaejo` VARCHAR(45) NULL,
  `resrn` VARCHAR(45) NULL,
  `edautor` VARCHAR(45) NULL,
  `edicion` DATETIME NULL,
  `actualizar` DATETIME NULL,
  PRIMARY KEY (`nacional_id`),
  INDEX `fk_NACIONAL_JERARQUIZACION1_idx` (`JERARQUIZACION_jerarquizacion_id` ASC),
  CONSTRAINT `fk_NACIONAL_JERARQUIZACION1`
    FOREIGN KEY (`JERARQUIZACION_jerarquizacion_id`)
    REFERENCES `cdc`.`JERARQUIZACION` (`jerarquizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`SUBNACIONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`SUBNACIONAL` ;

CREATE TABLE IF NOT EXISTS `cdc`.`SUBNACIONAL` (
  `subnacional_id` INT NOT NULL AUTO_INCREMENT,
  `JERARQUIZACION_jerarquizacion_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `subnacion` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `loctips` VARCHAR(45) NULL,
  `lestims` VARCHAR(45) NULL,
  `comlestims` VARCHAR(45) NULL,
  `abunds` VARCHAR(45) NULL,
  `comabunds` VARCHAR(45) NULL,
  `dists` VARCHAR(45) NULL,
  `comdists` VARCHAR(45) NULL,
  `leprots` VARCHAR(45) NULL,
  `comleprots` VARCHAR(45) NULL,
  `amenazs` VARCHAR(45) NULL,
  `comamenazs` VARCHAR(45) NULL,
  `otraconsids` VARCHAR(45) NULL,
  `rangos` VARCHAR(45) NULL,
  `fecharevrs` DATETIME NULL,
  `razonrs` VARCHAR(45) NULL,
  `necprotecs` VARCHAR(45) NULL,
  `necinvents` VARCHAR(45) NULL,
  `necmanejos` VARCHAR(45) NULL,
  `autored` VARCHAR(45) NULL,
  `edicion` DATETIME NULL,
  `actualizar` DATETIME NULL,
  PRIMARY KEY (`subnacional_id`),
  INDEX `fk_SUBNACIONAL_JERARQUIZACION1_idx` (`JERARQUIZACION_jerarquizacion_id` ASC),
  CONSTRAINT `fk_SUBNACIONAL_JERARQUIZACION1`
    FOREIGN KEY (`JERARQUIZACION_jerarquizacion_id`)
    REFERENCES `cdc`.`JERARQUIZACION` (`jerarquizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CARACTERIZACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CARACTERIZACION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CARACTERIZACION` (
  `caracterizacion_id` INT NOT NULL AUTO_INCREMENT,
  `ELEMENTO_elemento_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`caracterizacion_id`),
  INDEX `fk_CARACTERIZACION_ELEMENTO1_idx` (`ELEMENTO_elemento_id` ASC),
  CONSTRAINT `fk_CARACTERIZACION_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elemento_id`)
    REFERENCES `cdc`.`ELEMENTO` (`elemento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`PLANTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`PLANTA` ;

CREATE TABLE IF NOT EXISTS `cdc`.`PLANTA` (
  `planta_id` INT NOT NULL AUTO_INCREMENT,
  `CARACTERIZACION_caracterizacion_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `nombren` VARCHAR(45) NULL,
  `nomcomunn` VARCHAR(45) NULL,
  `comsubespn` VARCHAR(45) NULL,
  `taxasimiln` VARCHAR(45) NULL,
  `comidentn` VARCHAR(45) NULL,
  `comtaxn` VARCHAR(45) NULL,
  `rangog` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `aepeu` VARCHAR(45) NULL,
  `cites` VARCHAR(45) NULL,
  `uicn` VARCHAR(45) NULL,
  `rastreolen` VARCHAR(45) NULL,
  `protnacion` VARCHAR(45) NULL,
  `malezan` VARCHAR(45) NULL,
  `clasifinstn` VARCHAR(45) NULL,
  `comstatn` VARCHAR(45) NULL,
  `priinventn` VARCHAR(45) NULL,
  `necinventn` VARCHAR(45) NULL,
  `cominventn` VARCHAR(45) NULL,
  `respropn` VARCHAR(45) NULL,
  `elevminn` INT NULL,
  `elevmaxn` INT NULL,
  `disyuntn` VARCHAR(45) NULL,
  `periferican` VARCHAR(45) NULL,
  `comdistn` VARCHAR(45) NULL,
  `marinon` VARCHAR(45) NULL,
  `estuarinon` VARCHAR(45) NULL,
  `fluvialn` VARCHAR(45) NULL,
  `lacustren` VARCHAR(45) NULL,
  `palustren` VARCHAR(45) NULL,
  `terrestren` VARCHAR(45) NULL,
  `comhabn` VARCHAR(45) NULL,
  `comecoln` VARCHAR(45) NULL,
  `comfenoln` VARCHAR(45) NULL,
  `comrepn` VARCHAR(45) NULL,
  `commanejon` VARCHAR(45) NULL,
  `rcpnopc1` VARCHAR(45) NULL,
  `rcpnopc2` VARCHAR(45) NULL,
  `rcpnopc3` VARCHAR(45) NULL,
  `rcpnopc4` VARCHAR(45) NULL,
  `rcpnopc5` VARCHAR(45) NULL,
  `codfuente` VARCHAR(45) NULL,
  `cita` VARCHAR(45) NULL,
  `transparen` VARCHAR(45) NULL,
  `refg` VARCHAR(45) NULL,
  `refn` VARCHAR(45) NULL,
  `edicionn` DATETIME NULL,
  `autoredn` VARCHAR(45) NULL,
  `actualizan` DATETIME NULL,
  `nenea1` VARCHAR(45) NULL,
  `nenea2` VARCHAR(45) NULL,
  `nenea3` VARCHAR(45) NULL,
  `nenea4` VARCHAR(45) NULL,
  `nmara1` VARCHAR(45) NULL,
  `nmara2` VARCHAR(45) NULL,
  `nmara3` VARCHAR(45) NULL,
  `nmara4` VARCHAR(45) NULL,
  `nmaya1` VARCHAR(45) NULL,
  `nmaya2` VARCHAR(45) NULL,
  `nmaya3` VARCHAR(45) NULL,
  `nmaya4` VARCHAR(45) NULL,
  `njula1` VARCHAR(45) NULL,
  `njula2` VARCHAR(45) NULL,
  `njula3` VARCHAR(45) NULL,
  `njula4` VARCHAR(45) NULL,
  `nseta1` VARCHAR(45) NULL,
  `nseta2` VARCHAR(45) NULL,
  `nseta3` VARCHAR(45) NULL,
  `nseta4` VARCHAR(45) NULL,
  `nnova1` VARCHAR(45) NULL,
  `nnova2` VARCHAR(45) NULL,
  `nnova3` VARCHAR(45) NULL,
  `nnova4` VARCHAR(45) NULL,
  `neneb1` VARCHAR(45) NULL,
  `neneb2` VARCHAR(45) NULL,
  `neneb3` VARCHAR(45) NULL,
  `neneb4` VARCHAR(45) NULL,
  `nmarb1` VARCHAR(45) NULL,
  `nmarb2` VARCHAR(45) NULL,
  `nmarb3` VARCHAR(45) NULL,
  `nmarb4` VARCHAR(45) NULL,
  `nmayb1` VARCHAR(45) NULL,
  `nmayb2` VARCHAR(45) NULL,
  `nmayb3` VARCHAR(45) NULL,
  `nmayb4` VARCHAR(45) NULL,
  `njulb1` VARCHAR(45) NULL,
  `njulb2` VARCHAR(45) NULL,
  `njulb3` VARCHAR(45) NULL,
  `njulb4` VARCHAR(45) NULL,
  `nsetb1` VARCHAR(45) NULL,
  `nsetb2` VARCHAR(45) NULL,
  `nsetb3` VARCHAR(45) NULL,
  `nsetb4` VARCHAR(45) NULL,
  `nnovb1` VARCHAR(45) NULL,
  `nnovb2` VARCHAR(45) NULL,
  `nnovb3` VARCHAR(45) NULL,
  `nnovb4` VARCHAR(45) NULL,
  `nfeba1` VARCHAR(45) NULL,
  `nfeba2` VARCHAR(45) NULL,
  `nfeba3` VARCHAR(45) NULL,
  `nfeba4` VARCHAR(45) NULL,
  `nabra1` VARCHAR(45) NULL,
  `nabra2` VARCHAR(45) NULL,
  `nabra3` VARCHAR(45) NULL,
  `nabra4` VARCHAR(45) NULL,
  `njuna1` VARCHAR(45) NULL,
  `njuna2` VARCHAR(45) NULL,
  `njuna3` VARCHAR(45) NULL,
  `njuna4` VARCHAR(45) NULL,
  `nagoa1` VARCHAR(45) NULL,
  `nagoa2` VARCHAR(45) NULL,
  `nagoa3` VARCHAR(45) NULL,
  `nagoa4` VARCHAR(45) NULL,
  `nocta1` VARCHAR(45) NULL,
  `nocta2` VARCHAR(45) NULL,
  `nocta3` VARCHAR(45) NULL,
  `nocta4` VARCHAR(45) NULL,
  `ndica1` VARCHAR(45) NULL,
  `ndica2` VARCHAR(45) NULL,
  `ndica3` VARCHAR(45) NULL,
  `ndica4` VARCHAR(45) NULL,
  `nfebb1` VARCHAR(45) NULL,
  `nfebb2` VARCHAR(45) NULL,
  `nfebb3` VARCHAR(45) NULL,
  `nfebb4` VARCHAR(45) NULL,
  `nabrb1` VARCHAR(45) NULL,
  `nabrb2` VARCHAR(45) NULL,
  `nabrb3` VARCHAR(45) NULL,
  `nabrb4` VARCHAR(45) NULL,
  `njunb1` VARCHAR(45) NULL,
  `njunb2` VARCHAR(45) NULL,
  `njunb3` VARCHAR(45) NULL,
  `njunb4` VARCHAR(45) NULL,
  `nagob1` VARCHAR(45) NULL,
  `nagob2` VARCHAR(45) NULL,
  `nagob3` VARCHAR(45) NULL,
  `nagob4` VARCHAR(45) NULL,
  `noctb1` VARCHAR(45) NULL,
  `noctb2` VARCHAR(45) NULL,
  `noctb3` VARCHAR(45) NULL,
  `noctb4` VARCHAR(45) NULL,
  `ndicb1` VARCHAR(45) NULL,
  `ndicb2` VARCHAR(45) NULL,
  `ndicb3` VARCHAR(45) NULL,
  `ndicb4` VARCHAR(45) NULL,
  PRIMARY KEY (`planta_id`),
  INDEX `fk_PLANTA_CARACTERIZACION1_idx` (`CARACTERIZACION_caracterizacion_id` ASC),
  CONSTRAINT `fk_PLANTA_CARACTERIZACION1`
    FOREIGN KEY (`CARACTERIZACION_caracterizacion_id`)
    REFERENCES `cdc`.`CARACTERIZACION` (`caracterizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`VERTEBRADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`VERTEBRADO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`VERTEBRADO` (
  `vertebrado_id` INT NOT NULL AUTO_INCREMENT,
  `CARACTERIZACION_caracterizacion_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nacion` VARCHAR(45) NULL,
  `nombreg` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `nombren` VARCHAR(45) NULL,
  `nomcomunn` VARCHAR(45) NULL,
  `clasetax` VARCHAR(45) NULL,
  `orden` VARCHAR(45) NULL,
  `familia` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `comtaxg` VARCHAR(45) NULL,
  `comsubespn` VARCHAR(45) NULL,
  `rangog` VARCHAR(45) NULL,
  `cites` VARCHAR(45) NULL,
  `uicn` VARCHAR(45) NULL,
  `aepeu` VARCHAR(45) NULL,
  `fechaaepeu` DATETIME NULL,
  `endemismo` VARCHAR(45) NULL,
  `comstatg` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `protnacion` VARCHAR(45) NULL,
  `rastreolen` VARCHAR(45) NULL,
  `espdeportn` VARCHAR(45) NULL,
  `espcomern` VARCHAR(45) NULL,
  `pezdeport` VARCHAR(45) NULL,
  `ndeportpro` VARCHAR(45) NULL,
  `cazapieln` VARCHAR(45) NULL,
  `pesten` VARCHAR(45) NULL,
  `comstatn` VARCHAR(45) NULL,
  `elevminn` INT NULL,
  `elevmaxn` INT NULL,
  `comdistg` VARCHAR(45) NULL,
  `comdistn` VARCHAR(45) NULL,
  `residente` VARCHAR(45) NULL,
  `miglocal` VARCHAR(45) NULL,
  `migdist` VARCHAR(45) NULL,
  `repn` VARCHAR(45) NULL,
  `norepn` VARCHAR(45) NULL,
  `transmign` VARCHAR(45) NULL,
  `aparirregn` VARCHAR(45) NULL,
  `mign` VARCHAR(45) NULL,
  `commigg` VARCHAR(45) NULL,
  `commign` VARCHAR(45) NULL,
  `marino` VARCHAR(45) NULL,
  `estuarino` VARCHAR(45) NULL,
  `fluvial` VARCHAR(45) NULL,
  `lacustre` VARCHAR(45) NULL,
  `palustre` VARCHAR(45) NULL,
  `terrestre` VARCHAR(45) NULL,
  `subterran` VARCHAR(45) NULL,
  `factorespe` VARCHAR(45) NULL,
  `comhabg` VARCHAR(45) NULL,
  `comhabrep` VARCHAR(45) NULL,
  `comhabn` VARCHAR(45) NULL,
  `habitosalim` VARCHAR(45) NULL,
  `comalimg` VARCHAR(45) NULL,
  `comalimn` VARCHAR(45) NULL,
  `comecolg` VARCHAR(45) NULL,
  `comecoln` VARCHAR(45) NULL,
  `fenologia` VARCHAR(45) NULL,
  `comfenolg` VARCHAR(45) NULL,
  `comfenoln` VARCHAR(45) NULL,
  `colrep` VARCHAR(45) NULL,
  `comrepg` VARCHAR(45) NULL,
  `comrepn` VARCHAR(45) NULL,
  `commanejog` VARCHAR(45) NULL,
  `commanejon` VARCHAR(45) NULL,
  `usoeconom` VARCHAR(45) NULL,
  `longitud` INT NULL,
  `peso` INT NULL,
  `rcvnopc1` VARCHAR(45) NULL,
  `rcvnopc2` VARCHAR(45) NULL,
  `rcvnopc3` VARCHAR(45) NULL,
  `rcvnopc4` VARCHAR(45) NULL,
  `rcvnopc5` VARCHAR(45) NULL,
  `refg` VARCHAR(45) NULL,
  `refn` VARCHAR(45) NULL,
  `ediciong` DATETIME NULL,
  `actualizag` DATETIME NULL,
  `edicionn` DATETIME NULL,
  `actualizan` DATETIME NULL,
  `nenea` VARCHAR(45) NULL,
  `nabra` VARCHAR(45) NULL,
  `njula` VARCHAR(45) NULL,
  `nocta` VARCHAR(45) NULL,
  `neneb` VARCHAR(45) NULL,
  `nabrb` VARCHAR(45) NULL,
  `njulb` VARCHAR(45) NULL,
  `noctb` VARCHAR(45) NULL,
  `nfeba` VARCHAR(45) NULL,
  `nmaya` VARCHAR(45) NULL,
  `nagoa` VARCHAR(45) NULL,
  `nnova` VARCHAR(45) NULL,
  `nfebb` VARCHAR(45) NULL,
  `nmayb` VARCHAR(45) NULL,
  `nagob` VARCHAR(45) NULL,
  `nnovb` VARCHAR(45) NULL,
  `nmara` VARCHAR(45) NULL,
  `njuna` VARCHAR(45) NULL,
  `nseta` VARCHAR(45) NULL,
  `ndica` VARCHAR(45) NULL,
  `nmarb` VARCHAR(45) NULL,
  `njunb` VARCHAR(45) NULL,
  `nsetb` VARCHAR(45) NULL,
  `ndicb` VARCHAR(45) NULL,
  PRIMARY KEY (`vertebrado_id`),
  INDEX `fk_VERTEBRADO_CARACTERIZACION1_idx` (`CARACTERIZACION_caracterizacion_id` ASC),
  CONSTRAINT `fk_VERTEBRADO_CARACTERIZACION1`
    FOREIGN KEY (`CARACTERIZACION_caracterizacion_id`)
    REFERENCES `cdc`.`CARACTERIZACION` (`caracterizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`FUENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`FUENTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`FUENTE` (
  `fuente_id` INT NOT NULL AUTO_INCREMENT,
  `RASTREO_rastreo_id` INT NULL,
  `USUARIO_usuario_id` INT NULL,
  `naturalezadocumento` VARCHAR(1) NULL,
  `codfuente` VARCHAR(45) NULL,
  `cita` VARCHAR(45) NULL,
  `archivado` VARCHAR(45) NULL,
  `cobgeo` VARCHAR(45) NULL,
  `coords` VARCHAR(45) NULL,
  `coordn` VARCHAR(45) NULL,
  `coorde` VARCHAR(45) NULL,
  `coordo` VARCHAR(45) NULL,
  `resumen` VARCHAR(45) NULL,
  `publicacioncdc` TINYINT(1) NULL,
  `valor` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  `notadigest` VARCHAR(45) NULL,
  `actualizar` DATETIME NULL,
  `control` DATETIME NULL,
  `bcd` VARCHAR(45) NULL,
  `comunnat` TINYINT(1) NULL,
  `comunterr` TINYINT(1) NULL,
  `bosque` TINYINT(1) NULL,
  `sabana` TINYINT(1) NULL,
  `prado` TINYINT(1) NULL,
  `chaparral` TINYINT(1) NULL,
  `desierto` TINYINT(1) NULL,
  `alpino` TINYINT(1) NULL,
  `otroterr` TINYINT(1) NULL,
  `comunac` TINYINT(1) NULL,
  `palustre` TINYINT(1) NULL,
  `lacustre` TINYINT(1) NULL,
  `fluvial` TINYINT(1) NULL,
  `estuarino` TINYINT(1) NULL,
  `maritimo` TINYINT(1) NULL,
  `subterr` TINYINT(1) NULL,
  `flora` TINYINT(1) NULL,
  `floraac` TINYINT(1) NULL,
  `floraterr` TINYINT(1) NULL,
  `plnovasc` TINYINT(1) NULL,
  `plvasc` TINYINT(1) NULL,
  `microorg` TINYINT(1) NULL,
  `infositio` TINYINT(1) NULL,
  `fauna` TINYINT(1) NULL,
  `faunaac` TINYINT(1) NULL,
  `faunaterr` TINYINT(1) NULL,
  `moluscos` TINYINT(1) NULL,
  `insectos` TINYINT(1) NULL,
  `crustaceos` TINYINT(1) NULL,
  `otroartrop` TINYINT(1) NULL,
  `otroinvert` TINYINT(1) NULL,
  `peces` TINYINT(1) NULL,
  `anfibios` TINYINT(1) NULL,
  `reptiles` TINYINT(1) NULL,
  `aves` TINYINT(1) NULL,
  `mamiferos` TINYINT(1) NULL,
  `cienfisic` TINYINT(1) NULL,
  `fisiotopo` TINYINT(1) NULL,
  `hidrol` TINYINT(1) NULL,
  `geologia` TINYINT(1) NULL,
  `suelos` TINYINT(1) NULL,
  `clima` TINYINT(1) NULL,
  `biologia` TINYINT(1) NULL,
  `ecologia` TINYINT(1) NULL,
  `funecol` TINYINT(1) NULL,
  `diversnat` TINYINT(1) NULL,
  `inventario` TINYINT(1) NULL,
  `tecinvest` TINYINT(1) NULL,
  `am` TINYINT(1) NULL,
  `planmanejo` TINYINT(1) NULL,
  `tecmanejo` TINYINT(1) NULL,
  `estimpamb` TINYINT(1) NULL,
  `organprott` TINYINT(1) NULL,
  `herrprot` TINYINT(1) NULL,
  PRIMARY KEY (`fuente_id`),
  INDEX `fk_FUENTE_RASTREO1_idx` (`RASTREO_rastreo_id` ASC),
  INDEX `fk_FUENTE_USUARIO1_idx` (`USUARIO_usuario_id` ASC),
  UNIQUE INDEX `codfuente_UNIQUE` (`codfuente` ASC),
  CONSTRAINT `fk_FUENTE_RASTREO1`
    FOREIGN KEY (`RASTREO_rastreo_id`)
    REFERENCES `cdc`.`RASTREO` (`rastreo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUENTE_USUARIO1`
    FOREIGN KEY (`USUARIO_usuario_id`)
    REFERENCES `cdc`.`USUARIO` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`PROTOCOLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`PROTOCOLO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`PROTOCOLO` (
  `protocolo_id` INT NOT NULL AUTO_INCREMENT,
  `codigoe` VARCHAR(45) NULL,
  `ELEMENTO_elemento_id` INT NULL,
  `rangog` VARCHAR(45) NULL,
  `rangon` VARCHAR(45) NULL,
  `rangos` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `nomcomun` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`protocolo_id`),
  INDEX `fk_PROTOCOLO_ELEMENTO1_idx` (`ELEMENTO_elemento_id` ASC),
  CONSTRAINT `fk_PROTOCOLO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elemento_id`)
    REFERENCES `cdc`.`ELEMENTO` (`elemento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`FOTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`FOTO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`FOTO` (
  `foto_id` INT NOT NULL AUTO_INCREMENT,
  `ELEMENTO_elemento_id` INT NULL,
  `PLANTA_planta_id` INT NULL,
  `SITIO_sitio_id` INT NULL,
  `AREA_area_id` INT NULL,
  `VERTEBRADO_vertebrado_id` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `imagen` MEDIUMBLOB NULL,
  `posicion` INT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`foto_id`),
  INDEX `fk_FOTO_ELEMENTO1_idx` (`ELEMENTO_elemento_id` ASC),
  INDEX `fk_FOTO_PLANTA1_idx` (`PLANTA_planta_id` ASC),
  INDEX `fk_FOTO_SITIO1_idx` (`SITIO_sitio_id` ASC),
  INDEX `fk_FOTO_AREA1_idx` (`AREA_area_id` ASC),
  INDEX `fk_FOTO_VERTEBRADO1_idx` (`VERTEBRADO_vertebrado_id` ASC),
  CONSTRAINT `fk_FOTO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elemento_id`)
    REFERENCES `cdc`.`ELEMENTO` (`elemento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FOTO_PLANTA1`
    FOREIGN KEY (`PLANTA_planta_id`)
    REFERENCES `cdc`.`PLANTA` (`planta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FOTO_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FOTO_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FOTO_VERTEBRADO1`
    FOREIGN KEY (`VERTEBRADO_vertebrado_id`)
    REFERENCES `cdc`.`VERTEBRADO` (`vertebrado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`LOCALIZACION_has_SITIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`LOCALIZACION_has_SITIO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`LOCALIZACION_has_SITIO` (
  `LOCALIZACION_localizacion_id` INT NULL,
  `SITIO_sitio_id` INT NULL,
  INDEX `fk_LOCALIZACION_has_SITIO_SITIO1_idx` (`SITIO_sitio_id` ASC),
  INDEX `fk_LOCALIZACION_has_SITIO_LOCALIZACION1_idx` (`LOCALIZACION_localizacion_id` ASC),
  CONSTRAINT `fk_LOCALIZACION_has_SITIO_LOCALIZACION1`
    FOREIGN KEY (`LOCALIZACION_localizacion_id`)
    REFERENCES `cdc`.`LOCALIZACION` (`localizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCALIZACION_has_SITIO_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`SITIO_has_AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`SITIO_has_AREA` ;

CREATE TABLE IF NOT EXISTS `cdc`.`SITIO_has_AREA` (
  `SITIO_sitio_id` INT NULL,
  `AREA_area_id` INT NULL,
  INDEX `fk_SITIO_has_AREA_AREA1_idx` (`AREA_area_id` ASC),
  INDEX `fk_SITIO_has_AREA_SITIO1_idx` (`SITIO_sitio_id` ASC),
  CONSTRAINT `fk_SITIO_has_AREA_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SITIO_has_AREA_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`DISTRIBUCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`DISTRIBUCION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`DISTRIBUCION` (
  `distribucion_id` INT NOT NULL AUTO_INCREMENT,
  `PLANTA_planta_id` INT NULL,
  `VERTEBRADO_vertebrado_id` INT NULL,
  `codsubnac` VARCHAR(45) NULL,
  `nomsubnac` VARCHAR(45) NULL,
  `statsubnac` VARCHAR(45) NULL,
  PRIMARY KEY (`distribucion_id`),
  INDEX `fk_DISTRIBUCION_PLANTA1_idx` (`PLANTA_planta_id` ASC),
  INDEX `fk_DISTRIBUCION_VERTEBRADO1_idx` (`VERTEBRADO_vertebrado_id` ASC),
  CONSTRAINT `fk_DISTRIBUCION_PLANTA1`
    FOREIGN KEY (`PLANTA_planta_id`)
    REFERENCES `cdc`.`PLANTA` (`planta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DISTRIBUCION_VERTEBRADO1`
    FOREIGN KEY (`VERTEBRADO_vertebrado_id`)
    REFERENCES `cdc`.`VERTEBRADO` (`vertebrado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`PROTECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`PROTECCION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`PROTECCION` (
  `proteccion_id` INT NOT NULL AUTO_INCREMENT,
  `LOCALIZACION_localizacion_id` INT NULL,
  `codigoam` VARCHAR(45) NULL,
  `nombream` VARCHAR(45) NULL,
  `contenido` VARCHAR(45) NULL,
  PRIMARY KEY (`proteccion_id`),
  INDEX `fk_PROTECCION_LOCALIZACION1_idx` (`LOCALIZACION_localizacion_id` ASC),
  CONSTRAINT `fk_PROTECCION_LOCALIZACION1`
    FOREIGN KEY (`LOCALIZACION_localizacion_id`)
    REFERENCES `cdc`.`LOCALIZACION` (`localizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`DISPERSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`DISPERSION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`DISPERSION` (
  `dispersion_id` INT NOT NULL AUTO_INCREMENT,
  `PROTOCOLO_protocolo_id` INT NULL,
  `le` VARCHAR(45) NULL,
  `nommapanummarg` VARCHAR(45) NULL,
  `prov` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `ultobs` VARCHAR(45) NULL,
  PRIMARY KEY (`dispersion_id`),
  INDEX `fk_DISPERSION_PROTOCOLO1_idx` (`PROTOCOLO_protocolo_id` ASC),
  CONSTRAINT `fk_DISPERSION_PROTOCOLO1`
    FOREIGN KEY (`PROTOCOLO_protocolo_id`)
    REFERENCES `cdc`.`PROTOCOLO` (`protocolo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`LISTA_ELEMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`LISTA_ELEMENTO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`LISTA_ELEMENTO` (
  `lista_elemento_id` INT NOT NULL AUTO_INCREMENT,
  `AREA_area_id` INT NULL,
  `codigoe` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `codfuente` VARCHAR(45) NULL,
  PRIMARY KEY (`lista_elemento_id`),
  INDEX `fk_COMPONENTE_AREA1_idx` (`AREA_area_id` ASC),
  CONSTRAINT `fk_COMPONENTE_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`Observaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`Observaciones` ;

CREATE TABLE IF NOT EXISTS `cdc`.`Observaciones` (
  `observaciones_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `LOCALIZACION_localizacion_id` INT NULL,
  `SITIO_sitio_id` INT NULL,
  `AREA_area_id` INT NULL,
  `RASTREO_rastreo_id` INT NULL,
  PRIMARY KEY (`observaciones_id`),
  INDEX `fk_Oberservaciones_LOCALIZACION1_idx` (`LOCALIZACION_localizacion_id` ASC),
  INDEX `fk_Oberservaciones_SITIO1_idx` (`SITIO_sitio_id` ASC),
  INDEX `fk_Oberservaciones_AREA1_idx` (`AREA_area_id` ASC),
  INDEX `fk_Oberservaciones_RASTREO1_idx` (`RASTREO_rastreo_id` ASC),
  CONSTRAINT `fk_Oberservaciones_LOCALIZACION1`
    FOREIGN KEY (`LOCALIZACION_localizacion_id`)
    REFERENCES `cdc`.`LOCALIZACION` (`localizacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oberservaciones_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oberservaciones_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oberservaciones_RASTREO1`
    FOREIGN KEY (`RASTREO_rastreo_id`)
    REFERENCES `cdc`.`RASTREO` (`rastreo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`ARCHIVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`ARCHIVO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`ARCHIVO` (
  `archivo_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `departamento` VARCHAR(45) NULL,
  `localizacion` VARCHAR(45) NULL,
  `archivocdc` MEDIUMBLOB NULL,
  `FUENTE_fuente_id` INT NULL,
  PRIMARY KEY (`archivo_id`),
  INDEX `fk_Archivo_FUENTE1_idx` (`FUENTE_fuente_id` ASC),
  CONSTRAINT `fk_Archivo_FUENTE1`
    FOREIGN KEY (`FUENTE_fuente_id`)
    REFERENCES `cdc`.`FUENTE` (`fuente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`DISTRIBUCION2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`DISTRIBUCION2` ;

CREATE TABLE IF NOT EXISTS `cdc`.`DISTRIBUCION2` (
  `distribucion2_id` INT NOT NULL AUTO_INCREMENT,
  `codecoregn` VARCHAR(45) NULL,
  `statecoregn` VARCHAR(45) NULL,
  `codcuencan` VARCHAR(45) NULL,
  `statcuencan` VARCHAR(45) NULL,
  `PLANTA_planta_id` INT NULL,
  `VERTEBRADO_vertebrado_id` INT NULL,
  PRIMARY KEY (`distribucion2_id`),
  INDEX `fk_DISTRIBUCION2_PLANTA1_idx` (`PLANTA_planta_id` ASC),
  INDEX `fk_DISTRIBUCION2_VERTEBRADO1_idx` (`VERTEBRADO_vertebrado_id` ASC),
  CONSTRAINT `fk_DISTRIBUCION2_PLANTA1`
    FOREIGN KEY (`PLANTA_planta_id`)
    REFERENCES `cdc`.`PLANTA` (`planta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DISTRIBUCION2_VERTEBRADO1`
    FOREIGN KEY (`VERTEBRADO_vertebrado_id`)
    REFERENCES `cdc`.`VERTEBRADO` (`vertebrado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`MACSITIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`MACSITIO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`MACSITIO` (
  `macsitio_id` INT NOT NULL AUTO_INCREMENT,
  `codmacsitio` VARCHAR(45) NULL,
  `nommacsitio` VARCHAR(45) NULL,
  `SITIO_sitio_id` INT NULL,
  PRIMARY KEY (`macsitio_id`),
  INDEX `fk_MACSITIO_SITIO1_idx` (`SITIO_sitio_id` ASC),
  CONSTRAINT `fk_MACSITIO_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`SUBDIVISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`SUBDIVISION` ;

CREATE TABLE IF NOT EXISTS `cdc`.`SUBDIVISION` (
  `subdivision_id` INT NOT NULL AUTO_INCREMENT,
  `codsubdiv` VARCHAR(45) NULL,
  `nomsubdiv` VARCHAR(45) NULL,
  `nommapa` VARCHAR(45) NULL,
  `codmapa` VARCHAR(45) NULL,
  `SITIO_sitio_id` INT NULL,
  PRIMARY KEY (`subdivision_id`),
  INDEX `fk_SUBDIVISION_SITIO1_idx` (`SITIO_sitio_id` ASC),
  CONSTRAINT `fk_SUBDIVISION_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`LOTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`LOTE` (
  `lote_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`lote_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`SITIO_has_LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`SITIO_has_LOTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`SITIO_has_LOTE` (
  `sitio_lote_id` INT NOT NULL AUTO_INCREMENT,
  `SITIO_sitio_id` INT NULL,
  `LOTE_lote_id` INT NULL,
  INDEX `fk_SITIO_has_LOTE_LOTE1_idx` (`LOTE_lote_id` ASC),
  INDEX `fk_SITIO_has_LOTE_SITIO1_idx` (`SITIO_sitio_id` ASC),
  PRIMARY KEY (`sitio_lote_id`),
  CONSTRAINT `fk_SITIO_has_LOTE_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SITIO_has_LOTE_LOTE1`
    FOREIGN KEY (`LOTE_lote_id`)
    REFERENCES `cdc`.`LOTE` (`lote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`AREA_has_LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`AREA_has_LOTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`AREA_has_LOTE` (
  `AREA_area_id` INT NULL,
  `LOTE_lote_id` INT NULL,
  `area_lote_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_AREA_has_LOTE_LOTE1_idx` (`LOTE_lote_id` ASC),
  INDEX `fk_AREA_has_LOTE_AREA1_idx` (`AREA_area_id` ASC),
  PRIMARY KEY (`area_lote_id`),
  CONSTRAINT `fk_AREA_has_LOTE_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AREA_has_LOTE_LOTE1`
    FOREIGN KEY (`LOTE_lote_id`)
    REFERENCES `cdc`.`LOTE` (`lote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CONTACTO_has_FUENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CONTACTO_has_FUENTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CONTACTO_has_FUENTE` (
  `CONTACTO_contacto_id` INT NULL,
  `FUENTE_fuente_id` INT NULL,
  `contacto_fuente_id` INT NOT NULL AUTO_INCREMENT,
  `codfuente` VARCHAR(45) NULL,
  INDEX `fk_CONTACTO_has_FUENTE_FUENTE1_idx` (`FUENTE_fuente_id` ASC),
  INDEX `fk_CONTACTO_has_FUENTE_CONTACTO1_idx` (`CONTACTO_contacto_id` ASC),
  PRIMARY KEY (`contacto_fuente_id`),
  CONSTRAINT `fk_CONTACTO_has_FUENTE_CONTACTO1`
    FOREIGN KEY (`CONTACTO_contacto_id`)
    REFERENCES `cdc`.`CONTACTO` (`contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTACTO_has_FUENTE_FUENTE1`
    FOREIGN KEY (`FUENTE_fuente_id`)
    REFERENCES `cdc`.`FUENTE` (`fuente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CONTACTO_has_SITIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CONTACTO_has_SITIO` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CONTACTO_has_SITIO` (
  `contacto_sitio_id` INT NOT NULL AUTO_INCREMENT,
  `CONTACTO_contacto_id` INT NULL,
  `SITIO_sitio_id` INT NULL,
  INDEX `fk_CONTACTO_has_SITIO_SITIO1_idx` (`SITIO_sitio_id` ASC),
  INDEX `fk_CONTACTO_has_SITIO_CONTACTO1_idx` (`CONTACTO_contacto_id` ASC),
  PRIMARY KEY (`contacto_sitio_id`),
  CONSTRAINT `fk_CONTACTO_has_SITIO_CONTACTO1`
    FOREIGN KEY (`CONTACTO_contacto_id`)
    REFERENCES `cdc`.`CONTACTO` (`contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTACTO_has_SITIO_SITIO1`
    FOREIGN KEY (`SITIO_sitio_id`)
    REFERENCES `cdc`.`SITIO` (`sitio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CONTACTO_has_AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CONTACTO_has_AREA` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CONTACTO_has_AREA` (
  `contacto_area_id` INT NOT NULL AUTO_INCREMENT,
  `CONTACTO_contacto_id` INT NULL,
  `AREA_area_id` INT NULL,
  INDEX `fk_CONTACTO_has_AREA_AREA1_idx` (`AREA_area_id` ASC),
  INDEX `fk_CONTACTO_has_AREA_CONTACTO1_idx` (`CONTACTO_contacto_id` ASC),
  PRIMARY KEY (`contacto_area_id`),
  CONSTRAINT `fk_CONTACTO_has_AREA_CONTACTO1`
    FOREIGN KEY (`CONTACTO_contacto_id`)
    REFERENCES `cdc`.`CONTACTO` (`contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTACTO_has_AREA_AREA1`
    FOREIGN KEY (`AREA_area_id`)
    REFERENCES `cdc`.`AREA` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdc`.`CONTACTO_has_LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdc`.`CONTACTO_has_LOTE` ;

CREATE TABLE IF NOT EXISTS `cdc`.`CONTACTO_has_LOTE` (
  `CONTACTO_contacto_id` INT NULL,
  `LOTE_lote_id` INT NULL,
  `contacto_lote_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_CONTACTO_has_LOTE_LOTE1_idx` (`LOTE_lote_id` ASC),
  INDEX `fk_CONTACTO_has_LOTE_CONTACTO1_idx` (`CONTACTO_contacto_id` ASC),
  PRIMARY KEY (`contacto_lote_id`),
  CONSTRAINT `fk_CONTACTO_has_LOTE_CONTACTO1`
    FOREIGN KEY (`CONTACTO_contacto_id`)
    REFERENCES `cdc`.`CONTACTO` (`contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTACTO_has_LOTE_LOTE1`
    FOREIGN KEY (`LOTE_lote_id`)
    REFERENCES `cdc`.`LOTE` (`lote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
